In [40]:
import numpy as np
from numpy.linalg import eigh,norm

In [26]:
A = np.array([[2,0,0],
            [2,1,0],
            [0,-2,0]])
print(A)
print(A.shape)

[[ 2  0  0]
 [ 2  1  0]
 [ 0 -2  0]]
(3, 3)


In [5]:
ATA = A.T.dot(A)
print(ATA)

[[8 2 0]
 [2 5 0]
 [0 0 0]]


# EIGEN VALUES CALCULATION

In [28]:
eigen_values,eigen_vectors =eigh(ATA)
print(eigen_values)


[0. 4. 9.]


# SORTING THE EIGEN VALUES

In [17]:
sorted_indices=np.argsort(eigen_values)[::-1]
print(sorted_indices)
eigen_values=eigen_values[sorted_indices]
print(eigen_values)
eigen_vecotrs=eigen_vectors[:,sorted_indices]
print(eigen_vecotrs)

[0 1 2]
[9. 4. 0.]
[[ 0.          0.4472136  -0.89442719]
 [ 0.         -0.89442719 -0.4472136 ]
 [ 1.          0.         -0.        ]]


# SINGULAR VALUES

In [19]:
singular_values=np.sqrt(eigen_values)
print(singular_values)

[3. 2. 0.]


# CREATING DIAGRONAL MATRIX

In [32]:
S = np.zeros_like(A, dtype=float)
print(S.shape)
S[:A.shape[0], :A.shape[1]] = np.diag(singular_values)


(3, 3)


In [35]:
print(S[:A.shape[0],:A.shape[1]])

[[3. 0. 0.]
 [0. 2. 0.]
 [0. 0. 0.]]


In [37]:
U=A.dot(eigen_vectors)
print(U)

[[ 0.          0.89442719 -1.78885438]
 [ 0.          0.         -2.23606798]
 [ 0.          1.78885438  0.89442719]]


# NORMALIZE U

In [42]:
U /=norm(U,axis=0)
print(U)

[[        nan  0.4472136  -0.59628479]
 [        nan  0.         -0.74535599]
 [        nan  0.89442719  0.2981424 ]]


# CALCULATE VT

In [46]:
Vt=eigen_vectors.T
print(Vt)

[[ 0.          0.          1.        ]
 [ 0.4472136  -0.89442719  0.        ]
 [-0.89442719 -0.4472136  -0.        ]]


In [47]:
print("Matrix U (3x3):")
print(U)
print("\nMatrix S (3x3):")
print(S)
print("\nMatrix Vt (3x3):")
print(Vt)

Matrix U (3x3):
[[        nan  0.4472136  -0.59628479]
 [        nan  0.         -0.74535599]
 [        nan  0.89442719  0.2981424 ]]

Matrix S (3x3):
[[3. 0. 0.]
 [0. 2. 0.]
 [0. 0. 0.]]

Matrix Vt (3x3):
[[ 0.          0.          1.        ]
 [ 0.4472136  -0.89442719  0.        ]
 [-0.89442719 -0.4472136  -0.        ]]
